project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: false
execute:
  freeze: false  # set 'auto' to re-render only when source changes
website:
  title: "HSP 2024"
  favicon: favicon.ico
  navbar:
    left:
#      - href: index.qmd
#        text: Home
      - about.qmd
      - href: fodor-memorial-workshop.qmd
        text: Fodor Memorial Workshop
      - program.qmd
      - venue.qmd
      - presenters.qmd
      - registration.qmd
      - callforpapers.qmd
      - href: "https://hsp2024.creator-spring.com/"
        text: Souvenir Shop!
format:
  html:
    theme: 
      light: [cosmo, light.scss]
      dark: [darkly, dark.scss]
    toc: true
#    mainfont: Lato
resources:
  - 'abstracts/*.pdf'